config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos
  resources :locations
  resources :users do
    resources :tours do
      resources :steps
    end
  end

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show'

    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/favorite_tour.rb
class FavoriteTour < ActiveRecord::Base
  belongs_to :visitor, class_name: 'User'
  belongs_to :tour
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  has_many :tours
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :step
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :step
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :local, class_name: "User"
  belongs_to :visitor, class_name: "User"
end

app/models/saved_tour.rb
class SavedTour < ActiveRecord::Base
  belongs_to :visitor, class_name: 'User'
  belongs_to :tour
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :tour
  has_one :photo
  has_one :location

  validates :photo_id, presence: true
  validates :location_id, presence: true
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_many :steps
  belongs_to :local, class_name: "User"
  has_many :visitors, class_name: "User"
  belongs_to :interest
  has_many :saved_tours
  has_many :favorite_tours

  validates :photo_url, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tours, foreign_key: 'local_id'

  has_many :local_relationships, class_name: 'Relationship', foreign_key: 'visitor_id'
  has_many :visitor_relationships, class_name: 'Relationship', foreign_key: 'local_id'

  has_many :locals, through: :local_relationships
  has_many :visitors, through: :visitor_relationships
  has_many :saved_tours, foreign_key: 'visitor_id'
  has_many :favorite_tours, foreign_key: 'visitor_id'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :image_url)}
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :email, :password, :remember_me)}
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :username, :email, :current_password, :password, :password_confirmation, :image_url)}
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def create
    location = Location.new(
                            neighborhood: params[:neighborhood],
                            city: params[:city],
                            state: params[:state],
                            address: params[:address],
                            name: params[:name]
      )

    if location.save
      session[:location_id] = location.id
      render json: { saved: true }
    else
      render json: { saved: false, errors: location.errors }
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    photo = Photo.new(url: params[:photoAddress])
    p "***********************address: #{params[:photoAddress]} ******************************"
    if photo.save
      session[:photo_id] = photo.id
      render json: { saved: true, address: params[:photoAddress] }
    else
      render json: { saved: false }
    end
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
   skip_before_action :verify_authenticity_token

   def new
    @user = current_user
    @tour = Tour.find(params[:tour_id])
    @step_number = @tour.steps.count + 1
    @step = Step.new
  end

  def create
    tour = Tour.find(params[:tour_id])
    number_of_steps = tour.steps.count

    step = Step.new(
                    tour_id: tour.id,
                    text: params[:text],
                    number: ( number_of_steps + 1),
                    photo_id: session[:photo_id],
                    location_id: session[:location_id]
      )

    if step.save
      p '*' * 30
      p 'saved'
      p '*' * 30
      session[:photo_id] = nil
      session[:location_id] = nil
      redirect_to action: 'new'
    else
      p '*' * 30
      p 'didnt save'
      p '*' * 30
      @step = step
      @tour = tour
      @user = current_user
      @step_number = number_of_steps + 1

      redirect_to new_user_tour_step_path
    end
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

  def index
    @tours = Tour.all
    @user = current_user.id
  end

  def new
    @tour = Tour.new
  end

  def create

    @tour = Tour.new(name: params[:tour][:name], local_id: current_user.id, description: params[:tour][:description], photo_url: params[:tour][:photo_url])

    if @tour.save
      redirect_to "/users/#{current_user.id}/tours/#{@tour.id}/steps/new"
    else
      render new
    end
  end

  def show
    @tour = Tour.find(params[:id])
    @tour_steps = @tour.steps
    p '*' * 30
    p @tour_steps
    p '*' * 30
    @local = User.find(@tour.local_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @tours = Tour.all
    @saved_tours = @user.saved_tours
    @user_tours = @user.tours
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyEyes</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="header">
    <ul class="hmenu">
      <%= link_to image_tag("http://www.clker.com/cliparts/g/C/A/q/j/k/eye-biggest.svg", class: "head-icon"), root_path %>
      <%= render 'devise/menu/registration_items' %>|
      <%= render 'devise/menu/login_items' %>
    </ul>
  </div>

  <%= yield %>

  </body>
</html>

app/views/steps/new.html.erb
<h1 class="ta-c">New step for: <%= @tour.name %></h1>
<h2 class="ta-c"> Step number <%= @step_number %></h2>
<h3 class="ta-c"><%= link_to "Finish Tour", user_tour_path(@user.id, @tour.id), :method => :get %></h3>
<br><br>


  <div class="photo_box">
    <form class="photo_url" action="/photos" method="post">
      <label name="photo_url">Link for photograph: </label>
      <input type="text" class="photo_url_input_field" name="photo_url">
      <input type="submit" value="Add photo">
      <img class="displayed_photo" src="" style="height: 100px; width: 100px">
    </form>
  </div>

    <form class="location_submit_form" action="/locations" method="post">
      <div class="address_fields">
        <label name="name">Where are we going?</label>
        <input id="name" type="text" name="name">
        <br>
        <label name="neighborhood">Neighborhood</label>
        <input type="text" name="neighborhood">
        <br>
        <label name="address">Address</label>
        <input id="address" type="text" name="address">
        <br>
        <label name="city">City</label>
        <input id="city" type="text" name="city">
        <br>
        <label name="state">State</label>
        <input id="state" type="text" name="state">
        <br>
        <input type="submit" value="Add location">
      </div>
    </form>

  <div class="new_step">
    <form action="/users/<%= @user.id %>/tours/<%= @tour.id %>/steps" method="post">
      <label name="text">Description for this step:</label>
      <br>
      <textarea name="text" cols="50" rows="5"></textarea>
      <br>
      <div class="ta-r">
      <input type="submit" value = "Save Step">
    </form>


  </div>
</div>



<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>

<script>
  var directionsDisplay;
  var directionsService = new google.maps.DirectionsService();
  var map;

  function initialize() {
    directionsDisplay = new google.maps.DirectionsRenderer();
    var san_francisco = new google.maps.LatLng(37.7833, -122.4167);
    var mapOptions = {
      zoom: 12,
      center: san_francisco
    }
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    directionsDisplay.setMap(map);
  }


  google.maps.event.addDomListener(window, 'load', initialize);

</script>
<div class="map">
<div id="map-canvas"></div>

<div id="control_panel">

  <select multiple id="waypoints">

  </select>

    <input type="submit" onclick="calcRoute();">
  </div>
  <div id="directions_panel" style="margin:20px;background-color:#FFEE77;"></div>
</div>
</div>

app/views/tours/index.html.erb
<h1>Index list of tours</h1>

  <div class="tour-lists steps profile">
  <% @tours.each do |tour| %>
    <% user = tour.local_id %>
    <% local = User.find(1) %>
    <div class="tour steps">
      <p><img src=<%= "#{tour.photo_url}" %>></p>
      <p class="description"><%= link_to ("#{tour.name}"), user_tour_path(@user, tour.id) %>: <%= tour.description %> by <%= local.first_name %></p>
    </div>
  <% end %>
  </div>

  <!-- This page is a work in progress as far as css goes, but it's 4:30 am and I'm going to go to bed. Also, it will throw an error if you change the 1 on line 6 to 'user' because some of the tours don't have local_id's.  -->

app/views/tours/new.html.erb
<div class="new_tour">

  <h2 class="ta-c">Show Us What You See</h2>

  <%= form_for ([:user,@tour]) do |f| %>
    <div class="field">
      <%= f.label "Name your tour!" %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label "Add a Cover Photo!" %>
      <%= f.text_field :photo_url %>
    </div>

    <div class="field">
      <%= f.label "Describe your tour!" %>
    </div>

    <br>

    <%= f.text_area :description, :size=>"50%x10%", placeholder: "What are we going to be looking at on your tour?" %>
    <div class="ta-r">
      <%= f.submit "Create" %>
    </div>
  <% end %>

</div>

app/views/tours/show.html.erb
<h1 class="show-tour">
  <%= @tour.name %> by <%= @local.first_name %> <%= @local.last_name %>
</h1>
<div class="user-tours">
<% @tour_steps.each do |step| %>
  <div class="steps">
      <p>Step Number: <%= step.number %></p>
    <div class="step-photo">
      <% picture_id = step.photo_id %>
      <% image = Photo.find(picture_id) %>
      <p><img src=<%= "#{image.url}" %>></p>
    </div>
    <div class="description">
      Description: <%= step.text %>
      <% address_id = step.location_id %>
      <% address = Location.find(address_id) %>
      <br>Name: <%= address.name %>
      <br>Neighborhood: <%= address.neighborhood %>
      <br><%= address.address %>
      <br><%= address.city %>, <%= address.state %>
    </div>
  </div>
<% end %>
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>

<script>
  var directionsDisplay;
  var directionsService = new google.maps.DirectionsService();
  var map;

  function initialize() {
    directionsDisplay = new google.maps.DirectionsRenderer();
    var san_francisco = new google.maps.LatLng(37.7833, -122.4167);
    var mapOptions = {
      zoom: 12,
      center: san_francisco
    }
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    directionsDisplay.setMap(map);
  }

  function calcRoute() {
    var start = document.getElementById('start').value;
    var end = document.getElementById('end').value;
    // var start;
    // var end;
    var waypts = [];
    var checkboxArray = document.getElementById('waypoints');
    for (var i = 0; i < checkboxArray.length; i++) {
      if (checkboxArray.options[i].selected == true) {
        waypts.push({
            location:checkboxArray[i].value,
            stopover:true});
      }
    }

    var request = {
        origin: start,
        destination: end,
        waypoints: waypts,
        optimizeWaypoints: true,
        travelMode: google.maps.TravelMode.WALKING
    };
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
        var route = response.routes[0];
        var summaryPanel = document.getElementById('directions_panel');
        summaryPanel.innerHTML = '';
        // For each route, display summary information.
        for (var i = 0; i < route.legs.length; i++) {
          var routeSegment = i + 1;
          summaryPanel.innerHTML += '<b>Tour Section: ' + routeSegment + '</b><br>';
          summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
          summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
          summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
        }
      }
    });
  }

  google.maps.event.addDomListener(window, 'load', initialize);

</script>

<div class="map">

  <div id="map-canvas"></div>

  <div id="control_panel">

    <!-- <b>Start:</b>

    <select id="start">
      <option value="100 Bush St #101, San Francisco, CA 94104">Happy Donut 1</option>
    </select> -->


    <% @tour_steps.each do |step| %>
      <% location = Location.find(step.location_id) %>
      <% address = location.address + ' ' + location.city + ' ' + location.state%>

      <% if step.number == 1 %>
        <b>Start:</b>
        <select id="start">
          <option value=<%= "#{address}" %>><%= "#{location.name}" %></option>
        </select>
        <br>
      <% elsif step.number != @tour_steps.length - 1 %>
        <br>
        <b>Tour Steps:</b> <br>
        <i>(Ctrl-Click for multiple selection)</i> <br>
        <select multiple id="waypoints">
          <option value=<%= "#{address}" %>><%= "#{location.name}" %></option>
        </selct>
      <% else %>
        <b>End:</b>
        <select id="end">
          <option value=<%= "#{address}" %>><%= "#{location.name}" %></option>
        </select>
      <% end %>
    <% end %>
    <br>

    <input type="submit" onclick="calcRoute();">
  </div>

  <div id="directions_panel"></div>
</div></div>

app/views/users/show.html.erb
<div class="profile">
  <div class="personal">
    <img class="profile-pic" src=<%= "#{@user.image_url}" %>>


    <h1>Hello, <%= @user.first_name %>!</h1>
    <h3>Keep exploring new areas!</h3>
  </div>

  <div class="both-buttons">
    <div class="buttons">
      <%= button_to "Create New Tour", new_user_tour_path(@user.id), :method => :get %>
    </div>

    <div class="buttons">
      <%= button_to "Browse Tours", user_tours_path(@user.id), :method => :get %>
    </div>
    </div>
<div class="tour-lists">




    <h2>Tours You Created</h2>
      <% @user_tours.each do |tour| %>
        <div class="tour">
          <p><img src=<%= "#{tour.photo_url}" %>></p>
          <p><%= link_to ("#{tour.name}"), user_tour_path(@user.id, tour.id) %></p>
        </div>
      <% end %>


    </div>
  </div>
</div>